rough draft
codewizard-dt/city-cost-comparison pull request #15
Opened 2022-07-08 22:26 UTC by mmdoza002

2022-07-08 23:00 UTC, codewizard-dt requested changes
Looking great!!  I'm really digging what you've done

I would put both of the cards into the same section, and make that section a flex box so responsive styling is easier.  Also.. are they both supposed to the map-card class?  Semantically it doesn't make sense for the first one because it doesn't contain a map.  BUT if that class is doing important things, maybe just rename the class so it makes more sense.
<img width="317" alt="Screen Shot 2022-07-08 at 5 49 41 PM" src="https://user-images.githubusercontent.com/94571813/178079435-1cd7193b-baa8-4a9c-8eae-9c2172c67ba0.png">
On the index page... I see two things.  One is an overlap issues (screenshot) where the search bar is covering up the toggle.  It isn't doing that on the main branch.  I think you might be behind on the main branch. 
![Screen Shot 2022-07-08 at 5 53 14 PM](https://user-images.githubusercontent.com/94571813/178079906-a572b3ba-88a2-4b19-a7eb-c7a0d6e20e8d.png)
Also the index.css is missing some updated code from Matt.  In particular I see this rule is missing: 
![Screen Shot 2022-07-08 at 5 57 19 PM](https://user-images.githubusercontent.com/94571813/178079932-3ed71131-79a7-441a-84c8-e7a87df47034.png)
You are probably missing some other CSS rules that I didn't notice. Make sure your main is up to date and merge it into your branch :) then add the changes, commit, and push again :) No rush tho, I think it's great!

2022-07-09 19:33 UTC, littletonjeffrey approved these changes
Great job Martin

2022-07-09 19:34 UTC, littletonjeffrey approved these changes

2022-07-10 17:02 UTC, codewizard-dt approved these changes
This looks great :) I'll have to look at it in my browser tomorrow morning but I can tell the code is clean and well formatted so I'm going to approve it :). One very small change.. Just an #id issue
I<img width="669" alt="Screen Shot 2022-07-10 at 11 57 46 AM" src="https://user-images.githubusercontent.com/94571813/178154458-840dbe76-6a7b-4d98-ae48-8258fda03b2e.png">
The `input` and `form` elements both have event listeners attached, so they both need IDs.  Currently the JS code refers to elements `<input id="search" />` and `<form id="searchByName">`. If you have better (more descriptive) names for them feel free to use them.  I can update the references in JS to match, but they both need IDs please :)

2022-07-10 17:14 UTC, merged